/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing;

import java.awt.Color;

/**
 *
 * @author Aluno
 */
public class TelaComponentes extends javax.swing.JFrame {

    /**
     * Creates new form TelaComponentes
     */
    public TelaComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pbProgresso = new javax.swing.JProgressBar();
        btProgressoAumentar = new javax.swing.JButton();
        pbProgressoDiminuir = new javax.swing.JButton();
        btProgressoCinquenta = new javax.swing.JButton();
        ckSolteiro = new javax.swing.JCheckBox();
        btSolteiro = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btProgressoAumentar.setText("Aumentar");
        btProgressoAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProgressoAumentarActionPerformed(evt);
            }
        });

        pbProgressoDiminuir.setText("Diminuir");
        pbProgressoDiminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbProgressoDiminuirActionPerformed(evt);
            }
        });

        btProgressoCinquenta.setText("Valor50");
        btProgressoCinquenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProgressoCinquentaActionPerformed(evt);
            }
        });

        ckSolteiro.setText("Solteiro(a)");

        btSolteiro.setText("Ver situação");
        btSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSolteiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckSolteiro)
                        .addGap(18, 18, 18)
                        .addComponent(btSolteiro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pbProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btProgressoAumentar)
                        .addGap(18, 18, 18)
                        .addComponent(pbProgressoDiminuir)
                        .addGap(18, 18, 18)
                        .addComponent(btProgressoCinquenta)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btProgressoAumentar)
                        .addComponent(pbProgressoDiminuir)
                        .addComponent(btProgressoCinquenta))
                    .addComponent(pbProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckSolteiro)
                    .addComponent(btSolteiro))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pbProgressoDiminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbProgressoDiminuirActionPerformed
       pbProgresso.setValue(pbProgresso.getValue()-5);
    }//GEN-LAST:event_pbProgressoDiminuirActionPerformed

    private void btProgressoCinquentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProgressoCinquentaActionPerformed
        pbProgresso.setValue(50);
    }//GEN-LAST:event_btProgressoCinquentaActionPerformed

    private void btProgressoAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProgressoAumentarActionPerformed
       pbProgresso.setValue(pbProgresso.getValue()+10);
    }//GEN-LAST:event_btProgressoAumentarActionPerformed

    private void btSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSolteiroActionPerformed
        if (ckSolteiro.isSelected()) {
            ckSolteiro.setForeground(Color.GREEN);
        } else {
            ckSolteiro.setForeground(Color.RED);
        }
    }//GEN-LAST:event_btSolteiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProgressoAumentar;
    private javax.swing.JButton btProgressoCinquenta;
    private javax.swing.JButton btSolteiro;
    private javax.swing.JCheckBox ckSolteiro;
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar pbProgresso;
    private javax.swing.JButton pbProgressoDiminuir;
    // End of variables declaration//GEN-END:variables
}
