/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing.dominio;

import com.mycompany.projeto.swing.dominio.Exercicio08Dominio;

/**
 *
 * @author macos
 */
public class Exercicio08 extends javax.swing.JFrame {

    Exercicio08Dominio elevadorA = new Exercicio08Dominio();
    Exercicio08Dominio elevadorB = new Exercicio08Dominio();
    
    void atualizarElevadorA(){
        lbPessoas.setText(String.format("%d", elevadorA.passageiro));
        lbPeso.setText(String.format("%.2fKg", elevadorA.pesoTotal));
    }
    
    void atualizarElevadorB(){
        lbPessoasB.setText(String.format("%d", elevadorB.passageiro));
        lbPesoB.setText(String.format("%.2fKg", elevadorB.pesoTotal));
    }

    public Exercicio08() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btHomem = new javax.swing.JButton();
        btMulher = new javax.swing.JButton();
        btCrianca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbPessoas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPeso = new javax.swing.JLabel();
        btHomemB = new javax.swing.JButton();
        btMulherB = new javax.swing.JButton();
        btCriancaB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbPessoasB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbPesoB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btHomem.setText("Entrar homem");
        btHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomemActionPerformed(evt);
            }
        });

        btMulher.setText("Entrar mulher");
        btMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMulherActionPerformed(evt);
            }
        });

        btCrianca.setText("Entrar criança");
        btCrianca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriancaActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de pessoas no elevador");

        lbPessoas.setText("0");

        jLabel3.setText("Peso total do elevador");

        lbPeso.setText("0Kg");

        btHomemB.setText("Entrar homem");
        btHomemB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomemBActionPerformed(evt);
            }
        });

        btMulherB.setText("Entrar mulher");
        btMulherB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMulherBActionPerformed(evt);
            }
        });

        btCriancaB.setText("Entrar criança");
        btCriancaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriancaBActionPerformed(evt);
            }
        });

        jLabel2.setText("Total de pessoas no elevador");

        lbPessoasB.setText("0");

        jLabel4.setText("Peso total do elevador");

        lbPesoB.setText("0Kg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btHomem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btMulher)
                .addGap(18, 18, 18)
                .addComponent(btCrianca)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPeso)
                            .addComponent(lbPessoas)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(btMulherB)
                                .addGap(148, 148, 148))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPesoB)
                                    .addComponent(lbPessoasB)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btHomemB)
                                .addGap(170, 170, 170)
                                .addComponent(btCriancaB)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMulher)
                    .addComponent(btCrianca)
                    .addComponent(btHomem))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbPessoas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMulherB)
                    .addComponent(btCriancaB)
                    .addComponent(btHomemB))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbPessoasB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbPesoB))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomemActionPerformed
        elevadorA.sobeHomem();
        atualizarElevadorA();
    }//GEN-LAST:event_btHomemActionPerformed

    private void btMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMulherActionPerformed
        elevadorA.sobeMulher();
        atualizarElevadorA();
    }//GEN-LAST:event_btMulherActionPerformed

    private void btCriancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriancaActionPerformed
        elevadorA.sobeCrianca();
        atualizarElevadorA();
    }//GEN-LAST:event_btCriancaActionPerformed

    private void btHomemBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomemBActionPerformed
        elevadorB.sobeHomem();
        atualizarElevadorB();
    }//GEN-LAST:event_btHomemBActionPerformed

    private void btMulherBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMulherBActionPerformed
        elevadorB.sobeMulher();
        atualizarElevadorB();
    }//GEN-LAST:event_btMulherBActionPerformed

    private void btCriancaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriancaBActionPerformed
        elevadorB.sobeCrianca();
        atualizarElevadorB();
    }//GEN-LAST:event_btCriancaBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio08().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrianca;
    private javax.swing.JButton btCriancaB;
    private javax.swing.JButton btHomem;
    private javax.swing.JButton btHomemB;
    private javax.swing.JButton btMulher;
    private javax.swing.JButton btMulherB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbPesoB;
    private javax.swing.JLabel lbPessoas;
    private javax.swing.JLabel lbPessoasB;
    // End of variables declaration//GEN-END:variables
}
