/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.java.heranca;

/**
 *
 * @author Guilherme
 */
public class TelaPet extends javax.swing.JFrame {

    Pet animal_estimacao;
    
    /**
     * Creates new form TelaPet
     */
    public TelaPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAdotarCachorro = new javax.swing.JButton();
        btAdotarGato = new javax.swing.JButton();
        btBarulhoPet = new javax.swing.JButton();
        lbSla = new javax.swing.JLabel();
        lbBarulhoPet = new javax.swing.JLabel();
        lbNomePet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAdotarCachorro.setText("Adotar cachorro");
        btAdotarCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdotarCachorroActionPerformed(evt);
            }
        });

        btAdotarGato.setText("Adotar gato");
        btAdotarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdotarGatoActionPerformed(evt);
            }
        });

        btBarulhoPet.setText("Barulho do Pet");
        btBarulhoPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBarulhoPetActionPerformed(evt);
            }
        });

        lbSla.setText("Nomes provaveis:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdotarCachorro)
                        .addGap(104, 104, 104)
                        .addComponent(btAdotarGato))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSla)
                            .addComponent(btBarulhoPet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNomePet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbBarulhoPet)))
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdotarCachorro)
                    .addComponent(btAdotarGato))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSla)
                    .addComponent(lbNomePet))
                .addGap(38, 38, 38)
                .addComponent(btBarulhoPet)
                .addGap(18, 18, 18)
                .addComponent(lbBarulhoPet)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdotarCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdotarCachorroActionPerformed
        // TODO add your handling code here:
        
        animal_estimacao = new Cachorro();
        
        lbNomePet.setText(animal_estimacao.getNome());
        
    }//GEN-LAST:event_btAdotarCachorroActionPerformed

    private void btBarulhoPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBarulhoPetActionPerformed
        // TODO add your handling code here:
        
        lbBarulhoPet.setText(animal_estimacao.getSom());
        
    }//GEN-LAST:event_btBarulhoPetActionPerformed

    private void btAdotarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdotarGatoActionPerformed
        // TODO add your handling code here:
        
        animal_estimacao = new Gato();
        
        lbNomePet.setText(animal_estimacao.getNome());
        
        
    }//GEN-LAST:event_btAdotarGatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdotarCachorro;
    private javax.swing.JButton btAdotarGato;
    private javax.swing.JButton btBarulhoPet;
    private javax.swing.JLabel lbBarulhoPet;
    private javax.swing.JLabel lbNomePet;
    private javax.swing.JLabel lbSla;
    // End of variables declaration//GEN-END:variables
}
